#@TYPE: Machine
#@NAME: firmware
#@DESCRIPTION: firmware old custom board - not being used

include conf/machine/stm32mp25-mx.conf

# ärv samma overrides som CubeMX-maskinen använder
MACHINEOVERRIDES =. "stm32mp25-mx:"

# boot från SD
BOOTDEVICE_LABELS += "sdcard"

# boot via OP-TEE (standard för MP25)
#BOOTSCHEME_LABELS += "optee"

# CubeMX-projekt
CUBEMX_PROJECT = "mx/firmware"
CUBEMX_PROJECT_NAME = "firmware"

# DT-namn (utan .dts)
CUBEMX_DTB = "stm32mp257f-${CUBEMX_PROJECT_NAME}-mx"
