#@TYPE: Machine
#@NAME: watermelon-wine-1a
#@DESCRIPTION: Watermelon Wine 1A custom board

include conf/machine/stm32mp25-mx.conf

# ärv samma overrides som CubeMX-maskinen använder
MACHINEOVERRIDES =. "stm32mp25-mx:"

# boot från SD
BOOTDEVICE_LABELS += "sdcard"

# boot via OP-TEE (standard för MP25)
#BOOTSCHEME_LABELS += "optee"

# CubeMX-projekt
CUBEMX_PROJECT = "mx/watermelon-wine-1a"
CUBEMX_PROJECT_NAME = "watermelon-wine-1a"

# DT-namn (utan .dts)
CUBEMX_DTB = "stm32mp257f-${CUBEMX_PROJECT_NAME}-mx"
