FILESEXTRAPATHS:prepend := "${THISDIR}/files:"

SRC_URI += "file://0001-Add-IMSG-for-IAC.patch"

#EXTRA_OEMAKE += "CFG_STM32_EARLY_CONSOLE_UART=6"
#EXTRA_OEMAKE += "CFG_TEE_CORE_LOG_LEVEL=4"
#EXTRA_OEMAKE += "CFG_TEE_CORE_DEBUG=y"
