# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "watermelon-wine"
BBFILE_PATTERN_watermelon-wine = "^${LAYERDIR}/"
BBFILE_PRIORITY_watermelon-wine = "6"

LAYERSERIES_COMPAT_watermelon-wine = "scarthgap"
